# Site settings
title: Vespucci
email: vespucci@vespucciproject.org 
url: http://vespucciproject.org
description: "Vespucci is a free, cross-platform software package for spectroscopic data analaysis and imaging."

# Color settings (hex-codes with the leading hash-tag)
color:
  primary-dark: '#258C4B' #Pantone 10303 C
  links: '#000000'

# Footer settings
footer: Vespucci Project (Wright State University)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/VespucciProject/Vespucci

# Build settings
markdown: kramdown
permalink: pretty
